### ISSUE TITLE
Dependency Management

### ISSUE THREAD

**Issue by jurgenhaas** [crowdsecurity/php-remediation-engine#14]
Currently, the dependency to the other packages are very strict and difficult to upgrade. As the constraints don't allow for higher version numbers but require a very specific version, a `composer update` can easily fail, because the composer.lock file contains that earlier fixed version and doesn't allow to update to the new one, unless the lock file gets deleted first.

But that's not an ideal workflow for composer based applications.

Instead of declaring

```
    "require": {
        "crowdsec/capi-client": "0.11.0",
        "crowdsec/lapi-client": "0.4.0",
    },

```

it would be better to something like this:

```
    "require": {
        "crowdsec/capi-client": "^0.11",
        "crowdsec/lapi-client": "^0.4",
    },

```

However, we've also seen issues with 0-based version numbers in the past. So the extended version of the question would be, when you're planning to go for something like 1.0.0-alpha at least?

**Comment by julienloizelet** [comment]
Hi @jurgenhaas,
Thanks for your message.

I will discuss with @rr404 to see when we should release a first "public and stable" `1.0.0` release (for each package and sub package).

To briefly explain why we are using a 0.x.y version: we are trying to follow some rules of a semantic versioning and, as we 
were still in development phase, we used the 0 version as it is mentioned in [the paragraph 4 of this resource](https://semver.org/spec/v2.0.0.html#spec-item-4). 
Thus, as `Anything MAY change at any time.` : we thought that it was better to strictly control the dependency.

Deciding that the version is stable (so we can have a first `1.0.0`) is quite subjective but,  [as it is now used in production,I guess we have to do this soon](https://semver.org/spec/v2.0.0.html#how-do-i-know-when-to-release-100).

**Comment by jurgenhaas** [comment]
Hi @julienloizelet 

Any news on this? Just asking because I'd like to start promoting our integration in the Drupal community but would like to get to a release-candidate stage first.

**Comment by julienloizelet** [comment]
Hi @jurgenhaas,
I should release all packages (`capi-client`, `lapi-client` and `remediation-engine`) in a first stable version `1.0.0` tomorrow.

I will confirm here when these releases are effective.

Thanks

**Comment by julienloizelet** [comment]
Hi @jurgenhaas,

Release `1.0.0` has been published.

Thanks

**Comment by jurgenhaas** [comment]
This is great, thanks @julienloizelet

**Comment by jurgenhaas** [comment]
Drupal integration 1.0.0-RC1 just got pubsliehd too: https://www.drupal.org/project/crowdsec
