### ISSUE TITLE
Trying to get in touch with Julien Devouassoud

### ISSUE THREAD

**Issue by jurgenhaas** [crowdsecurity/php-remediation-engine#17]
Sorry, to mis-use this channel for this approach, but I'm trying to get hold of Julien Devouassoud and all channels I have seem to be failing. He wrote to me and I responded and also send emails some time ago. No response at all and I'm worries that my email isn't getting through to him.

Also tried to reach him on Slack, no response either.

Could someone here in this issue queue who has a chance trying to ping him and letting him and me know, how we could communicate efficiently? Thanks in advance.

**Comment by LaurenceJJones** [comment]
@rr404 tagging for coverage

Hey! I'm laurence from crowdsec support

**Comment by jurgenhaas** [comment]
Thanks @LaurenceJJones
